sp_bower:
    bin: "%spbower_path%"
    install_on_warmup: true
    assetic:
        enabled: true
        nest_dependencies: false
        filters:
            css:
                - cssrewrite
    bundles:
        AppBundle:
            config_dir: "%kernel.root_dir%/../"
            asset_dir: "%kernel.root_dir%/../bower_components"
            cache:
                id: ~
                directory: "%kernel.root_dir%/../var/cache"

assetic:
    bundles: [AppBundle, FOSUserBundle]
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        uglifyjs2:
            bin: "%uglify_js_path%"
        uglifycss:
            bin: "%uglify_css_path%"
        cssrewrite: ~
    assets:
        # base
        template_css:
            inputs:
                - '%kernel.root_dir%/../bower_components/bootstrap/dist/css/bootstrap.css'
                - '@AppBundle/Resources/public/base/css/index.css'

        template_js:
            inputs:
                - '@jquery_js'
                - '@bootstrap_js'
        reframe_js:
            inputs: '%kernel.root_dir%/../bower_components/reframe.js/dist/reframe.min.js'

        # fonts
        #font (bootstrap) glyphicons-halflings-regular
        fonts_glyphicons_halflings_regular_eot:
            inputs: '%kernel.root_dir%/../bower_components/bootstrap/fonts/glyphicons-halflings-regular.eot'
            output: 'fonts/glyphicons-halflings-regular.eot'
        fonts_glyphicons_halflings_regular_svg:
            inputs: '%kernel.root_dir%/../bower_components/bootstrap/fonts/glyphicons-halflings-regular.svg'
            output: 'fonts/glyphicons-halflings-regular.svg'
        fonts_glyphicons_halflings_regular_ttf:
            inputs: '%kernel.root_dir%/../bower_components/bootstrap/fonts/glyphicons-halflings-regular.ttf'
            output: 'fonts/glyphicons-halflings-regular.ttf'
        fonts_glyphicons_halflings_regular_woff:
            inputs: '%kernel.root_dir%/../bower_components/bootstrap/fonts/glyphicons-halflings-regular.woff'
            output: 'fonts/glyphicons-halflings-regular.woff'
        fonts_glyphicons_halflings_regular_woff2:
            inputs: '%kernel.root_dir%/../bower_components/bootstrap/fonts/glyphicons-halflings-regular.woff2'
            output: 'fonts/glyphicons-halflings-regular.woff2'

        #font font_awesome
        font_awesome_css:
            inputs: '%kernel.root_dir%/../bower_components/font-awesome/css/font-awesome.css'
        fonts_font_awesome_otf:
            inputs: '%kernel.root_dir%/../bower_components/font-awesome/fonts/FontAwesome.otf'
            output: 'fonts/FontAwesome.otf'
        fonts_font_awesome_eot:
            inputs: '%kernel.root_dir%/../bower_components/font-awesome/fonts/fontawesome-webfont.eot'
            output: 'fonts/fontawesome-webfont.eot'
        fonts_font_awesome_svg:
            inputs: '%kernel.root_dir%/../bower_components/font-awesome/fonts/fontawesome-webfont.svg'
            output: 'fonts/fontawesome-webfont.svg'
        fonts_font_awesome_ttf:
            inputs: '%kernel.root_dir%/../bower_components/font-awesome/fonts/fontawesome-webfont.ttf'
            output: 'fonts/fontawesome-webfont.ttf'
        fonts_font_awesome_woff:
            inputs: '%kernel.root_dir%/../bower_components/font-awesome/fonts/fontawesome-webfont.woff'
            output: 'fonts/fontawesome-webfont.woff'
        fonts_font_awesome_woff2:
            inputs: '%kernel.root_dir%/../bower_components/font-awesome/fonts/fontawesome-webfont.woff2'
            output: 'fonts/fontawesome-webfont.woff2'

        #plugin select2
        select2_css:
            inputs: '%kernel.root_dir%/../bower_components/select2/dist/css/select2.min.css'

        select2_bootstrap_theme:
            inputs: '%kernel.root_dir%/../bower_components/select2-bootstrap-theme/dist/select2-bootstrap.min.css'

        select2_full_js:
            inputs: '%kernel.root_dir%/../bower_components/select2/dist/js/select2.full.min.js'
