sp_bower:
    bin: "%spbower_path%"
    install_on_warmup: true
    assetic:
        enabled: true
        nest_dependencies: false
        filters:
            css:
                - cssrewrite
    bundles:
        AppBundle:
            config_dir: "%kernel.root_dir%/../"
            asset_dir: "%kernel.root_dir%/../bower_components"
            cache:
                id: ~
                directory: "%kernel.root_dir%/../var/cache"

assetic:
    bundles: [AppBundle, FOSUserBundle]
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        uglifyjs2:
            bin: "%uglify_js_path%"
        uglifycss:
            bin: "%uglify_css_path%"
        cssrewrite: ~
    assets:
        template_css:
            inputs:
                - '%kernel.root_dir%/../bower_components/bootstrap/dist/css/bootstrap.css'
                - '@AppBundle/Resources/public/base/css/index.css'

        template_js:
            inputs:
                - '@jquery_js'
                - '@bootstrap_js'
        #font font_awesome
        font_awesome_css:
            inputs: '%kernel.root_dir%/../bower_components/font-awesome/css/font-awesome.css'
