app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# app/config/routing.yml
# hwi_oauth_redirect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#     prefix:   /connect
#
# hwi_oauth_connect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#     prefix:   /connect
#
# hwi_oauth_login:
#     resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#     prefix:   /login

draft:
    type:     rest
    resource: "@AppBundle/Controller/DraftApiController.php"
    prefix:   /api

bookmark:
    type:     rest
    resource: "@AppBundle/Controller/BookmarkApiController.php"
    prefix:   /api
