# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check

            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                    github:             "/login/check-github"
                login_path:        /login
                # use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: my_user_provider
            logout:
                path: fos_user_security_logout
                target: /login
            anonymous:    true

        login:
            pattern:  ^/login$
            security: false
            remember_me:
                secret:  "%secret%"
                lifetime: 31536000
                path:     /
                domain:   .%base_host%

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    # access_control:
    #     - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/login/check-github, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - { path: ^/admin/, role: ROLE_ADMIN }
    #     - { path: ^/, role: ROLE_USER }

    # access_control:
    #     - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
