services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    #utils
    draft_util:
        class: AppBundle\Util\DraftUtil
        autowire: true
        arguments:
            -
                draft_per_page: "%draft_per_page%"

    bookmark_util:
        class: AppBundle\Util\BookmarkUtil
        autowire: true
        arguments:
            -
                bookmark_per_page: "%bookmark_per_page%"
